In [270]:
import numpy as np
#Sigmoid func

def sigmoid(z):
    return 1/(1 + np.exp(- z))

print(sigmoid(0))
print(sigmoid(2))

0.5
0.8807970779778823


In [271]:
import numpy as np

#Init func

def initialize_with_zeros(dim):
    return np.zeros([dim, 1]), 0

c, d = initialize_with_zeros(2)
print(d)
print(c)

0
[[0.]
 [0.]]


In [272]:
import numpy as np

def propagate(w, b, X, Y):
    z = np.dot(w.T,X) + b
    a = sigmoid(z)
    dz = a - Y
    dw = 1 / X.shape[1] * np.dot(X,dz.T)
    db = 1 / X.shape[1] * np.sum(dz)
    cost = -1 / X.shape[1] * np.sum(np.dot(np.log(a), Y.T) + np.dot(np.log(1-a), (1-Y.T)))
    return dw, db, cost
print(propagate(np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])))

(array([[0.99845601],
       [2.39507239]]), 0.001455578136784208, 5.801545319394553)


In [273]:
import numpy as np
def optimize(w, b, X, Y, num_iterations, learning_rate):
    costs = []
    for i in range(num_iterations):
        dw, db, cost = propagate(w, b, X, Y)
        w -= dw * learning_rate
        b -= db * learning_rate
        costs.append(cost)
    params = {'w': w, 'b': b}
    grads = {'dw': dw, 'db': db}
    return params, grads, costs
params1, grads1, costs1 = (optimize(np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]]), num_iterations= 100, learning_rate = 0.009))
print(params1)
print("\n")
print(grads1)
print("\n")
print(costs1)

{'w': array([[0.19033591],
       [0.12259159]]), 'b': 1.9253598300845747}


{'dw': array([[0.67752042],
       [1.41625495]]), 'db': 0.21919450454067652}


[5.801545319394553, 5.7409505028093335, 5.680375426895575, 5.619821667177627, 5.559290922630777, 5.4987850248644605, 5.4383059480708145, 5.3778558196064505, 5.31743693118918, 5.257051750930273, 5.1967029360407295, 5.136393346354229, 5.0761260586313774, 5.015904381700862, 4.955731872427952, 4.895612352538272, 4.835549926277942, 4.7755489989189925, 4.71561429608081, 4.6557508838423285, 4.595964189588867, 4.5362600235376345, 4.476644600852061, 4.417124564226807, 4.357707006833278, 4.298399495423375, 4.239210093432046, 4.180147383816733, 4.121220491375143, 4.062439104215671, 4.003813494033474, 3.9453545347773966, 3.88707371925397, 3.82898317317329, 3.7710956660899897, 3.7134246186439928, 3.6559841054874314, 3.598788853232609, 3.5418542327531086, 3.485196245157411, 3.4288315007655084, 3.3727771904490416, 3.3170510487520035, 3.2616713082

In [274]:
def predict(w, b, X):
    z = np.dot(w.T,X) + b
    Y_prediction = sigmoid(z)
    Y_prediction[0] = [1 if item > 0.5 else 0  
         for item in Y_prediction[0]]
    return Y_prediction
print(predict(np.array([[0.1124579],[0.23106775]]), - 0.3, np.array([[1.,-1.1,-3.2],[1.2,2.,0.1]])))

[[1. 1. 0.]]


In [275]:
from sklearn import metrics
def model(X_train, Y_train, X_test, Y_test, num_iterations = 2000, learning_rate = 0.5):
    w, b = initialize_with_zeros(X_train.shape[0])
    params, gards, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate)
    Y_pred = predict(params['w'], (params['b']), X_test)
    accuracy =  metrics.accuracy_score(Y_test,Y_pred[0])
    d = {'w': params['w'], 'b': params['b'], 'accuracy': accuracy, 'costs': costs}
    return d

In [277]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

#Read data from CSV file
df = pd.read_csv('diabetes.csv')

#Isolate the features columns, normalise and convert to numpty array
features = df.drop(['Outcome'], axis = 1 )
features = ((features - features.mean())/features.std())
X = np.array(features)

#Isolate the classification (1/0) column
Y = np.array(df['Outcome'])

#Split features/classification to train/test data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=0) 
d = model(X_train.T, Y_train.T, X_test.T, Y_test.T)

print(d)
                

[[1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0.
  0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.
  0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]]
[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0
 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1
 0 1 1 1 0 0 0]
{'w': array([[ 